# Admin Rooms
admin_index:
    path:     /
    defaults: { _controller: AdminBundle:Admin:index }

admin_room_editor:
    path:     /room_editor/{roomId}
    defaults: { _controller: AdminBundle:Admin:roomEditor }

admin_room_create:
    path:     /room_editor
    defaults: { _controller: AdminBundle:Admin:roomEditor }

admin_room_remove:
    path:     /room_remove/{roomId}
    defaults: { _controller: AdminBundle:Admin:roomRemove }

admin_rooms:
    path:     /rooms
    defaults: { _controller: AdminBundle:Admin:rooms }

admin_physical_rooms:
    path:     /physical_rooms
    defaults: { _controller: AdminBundle:PhysicalRoomAdmin:physicalRooms }

admin_physical_room_editor:
    path:     /physical_room_editor/{physicalRoomId}
    defaults: { _controller: AdminBundle:PhysicalRoomAdmin:physicalRoomEditor, physicalRoomId: null }

admin_physical_room_remove:
    path:     /physical_room_remove/{physicalRoomId}
    defaults: { _controller: AdminBundle:PhysicalRoomAdmin:physicalRoomRemove }

admin_room_bookings:
    path:     /room_bookings
    defaults: { _controller: AdminBundle:RoomBookingAdmin:bookings }

admin_room_booking_editor:
    path:     /room_booking_editor/{bookingId}
    defaults: { _controller: AdminBundle:RoomBookingAdmin:bookingEditor, bookingId: null }

admin_room_booking_remove:
    path:     /room_booking_remove/{bookingId}
    defaults: { _controller: AdminBundle:RoomBookingAdmin:bookingRemove }

admin_room_booking_confirm:
    path:     /room_booking_remove/{bookingId}
    defaults: { _controller: AdminBundle:RoomBookingAdmin:bookingConfirm }


# Posts
admin_feedbacks:
    path:     /feedbacks
    defaults: { _controller: AdminBundle:Admin:feedbacks }

admin_feedback:
    path:     /feedback/{feedbackId}
    defaults: { _controller: AdminBundle:Admin:feedback }


admin_feedback_remove:
    path:     /feedback_remove/{feedbackId}
    defaults: { _controller: AdminBundle:Admin:feedbackRemove }


admin_site_setting:
    path:     /site_settings
    defaults: { _controller: AdminBundle:Admin:siteSettings }



# Admin Images
admin_images_upload:
    path:     /images_upload
    defaults: { _controller: AdminBundle:Admin:imagesUpload }

# Admin Images
admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Admin:login }

# Admin Images
admin_images_box:
    path:     /images_box
    defaults: { _controller: AdminBundle:Admin:imagesBox }

admin_images_modal:
    path:     /images_modal
    defaults: { _controller: AdminBundle:Admin:imagesModal }

admin_image_remove:
    path:     /image_remove/{imageId}
    defaults: { _controller: AdminBundle:Admin:imageRemove }

admin_image_editor:
    path:     /image_editor/{imageId}
    defaults: { _controller: AdminBundle:Admin:imageEditor }

admin_images:
    path:     /images
    defaults: { _controller: AdminBundle:Admin:images }

# Post Admin
admin_posts:
    path:     /posts
    defaults: { _controller: AdminBundle:PostAdmin:posts }

admin_post_editor:
    path:     /post_editor/{postId}
    defaults: { _controller: AdminBundle:PostAdmin:postEditor }

admin_create_post:
    path:     /post_editor
    defaults: { _controller: AdminBundle:PostAdmin:postEditor }

admin_post_remove:
    path:     /post_remove/{postId}
    defaults: { _controller: AdminBundle:PostAdmin:postRemove }

admin_setting_editor:
    path:     /setting_editor
    defaults: { _controller: AdminBundle:SettingAdmin:settingEditor }

# Reviews
admin_reviews:
    path:     /reviews
    defaults:
        _controller: AdminBundle:ReviewAdmin:reviews
admin_review_editor:
    path:     /review_editor/{reviewId}
    defaults: { _controller: AdminBundle:ReviewAdmin:reviewEditor }

admin_review_create:
    path:     /review_editor/create
    defaults: { _controller: AdminBundle:ReviewAdmin:reviewEditor }

admin_review_remove:
    path:     /review_remove/{reviewId}
    defaults: { _controller: AdminBundle:ReviewAdmin:reviewRemove }
